name: Build and test

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build_and_test:
    timeout-minutes: 10
    name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment: production

    strategy:
      matrix:
        node: ['18.x', '20.x']
        os: [ubuntu-latest]

    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Prettier check
        run: pnpm prettier:check

      - name: Build packages
        run: pnpm build

      - name: Run test
        run: pnpm test
